version: '3.9'
services:
  db:
    container_name: mysql
    # image: mysql/mysql-server:latest
    image: mysql:8.0
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mlflow
    # restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
     - net
  
  # mlflow:
  #   container_name: mlflow
  #   image: mlflow:v2.0.1
  #   ports:
  #    - "5000:5000"
  #   networks:
  #     - net
  #   command:
  #   -  mlflow ui --backend-store-uri mysql+pymysql://root:example@db:3306/mlflow 
    
networks:
  net:
    driver: bridge

volumes:
  mysql-data:
